### ISSUE TITLE
Stream button covering other buttons or spotify pause button

### ISSUE THREAD

**Issue by ReaperCalli** [NYRI4/Couve#3] opened 2021-06-16 11:00 UTC
![image](https://user-images.githubusercontent.com/59681368/122207465-c0533800-ced4-11eb-80f3-c990ef10f572.png)
![image](https://user-images.githubusercontent.com/59681368/122207757-0b6d4b00-ced5-11eb-8820-325932da3b32.png)
These are the problems that I have with the theme but overall its really nice.
Edit: Typo lol

**Comment by NYRI4** [comment] 2021-06-16 12:06
The stream button will be displayed here now
![image](https://user-images.githubusercontent.com/65369563/122215821-fd570480-ceab-11eb-9254-6c3e42eb635f.png)

**Comment by ReaperCalli** [comment] 2021-06-16 13:26
Thanks for the fix though it covers the game activity toggle plugin that not everyone use. Can I ask how to move it a bit to the left?
![image](https://user-images.githubusercontent.com/59681368/122227456-76c11800-cee9-11eb-9c35-d1079bb2f124.png)

**Comment by iTsuneko** [comment] 2021-06-16 13:29
This also resulted in having custom statuses and the stream button overlapping.

![image](https://user-images.githubusercontent.com/86003660/122227637-a4a65c80-cee9-11eb-9ef5-b5fef0ab1ec9.png)

**Comment by NYRI4** [comment] 2021-06-16 13:59
ah shit forgot that wonderful plugin exist

**Comment by NYRI4** [comment] 2021-06-18 18:07
Ok if you really want to use Game Activity Toggle, switch to Powercord, then you will have the option to display it in the status picker. For the custom status overlap, this should be fixed as of now. For the BetterDiscord version, DevilBro did not add something to know whether you have this plugins or not, not even to differentiate it from the other user buttons. So as long as plugins developers won't give a fuck about theme developers, I can't and won't give support to those trashy plugins.

**Comment by NYRI4** [comment] 2021-06-18 21:18
Update : After I talked to DevilBro, he's finally adding a class for it, and I'm for now using a messy but working way, thanks to his support. Since the problem is fixed, I'm closing this issue.

**Closed by NYRI4** 2021-06-18 21:18 UTC
